
version: 2.1
orbs:
  android: circleci/android@2.1.2
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:

    docker:
      # specify the version you desire here
      - image: cimg/android:2023.02
      # - image: circleci/android:api-28
      # - image: circleci/openjdk:latest


    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx4096m
    # Add steps to the job

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "androidlibrary_lib/build.gradle" }}

      - run: 
          name: change the permission
          command: chmod +x ./gradlew

      - run: 
          name: download gradle dependencies
          command: ./gradlew androidDependencies 

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "androidlibrary_lib/build.gradle" }}

      # build the androidlib
      - run: 
          name: build project
          command: ./gradlew clean assemble

      # run tests!
      - run: 
          name: gradle unit tests
          command: ./gradlew test
 
  android-test:
    executor:
      name: android/android-machine
      tag: "202102-01"
      resource-class: large

    steps:
      - checkout

      # - android/create-avd:
      #     avd-name: myavd
      #     install: true
      # #     # test-command: ./gradlew connectedAndroidTest
      #     system-image: system-images;android-30;google_apis;x86 
      # - android/start-emulator:
      #     avd-name: myavd
      # - android/start-emulator-and-run-tests:
      #     # emulator-version: "30.6.4"
      #     avd-name: myavd
      #     # wait-for-boot: 600
      #     test-command: ./gradlew connectedAndroidTest
      # # -  android/start-emulator:
      #     avd-name: myavd
      #     no-window: true
      # - run:
      #     name: run android test
      #     command:  |
      # #       ./gradlew connectedAndroidTest --scan
          # test-command: ./gradlew connectedAndroidTest
      #  - android/run-ui-tests:
          # system-image: system-images;android-28;default;x86
      - run:
          name: installing emulator and Running Instrumentation tests
          command:  |
            sdkmanager "platform-tools" "platforms;android-29" "build-tools;30.0.0" "emulator"
            sdkmanager "system-images;android-29;google_apis;x86"
            echo no | avdmanager create avd -n test-emulator -k "system-images;android-29;google_apis;x86"
            emulator -avd test-emulator -noaudio -no-boot-anim -gpu off -no-window &
            adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
            adb shell wm dismiss-keyguard
            sleep 1
            adb shell settings put global window_animation_scale 0
            adb shell settings put global transition_animation_scale 0
            adb shell settings put global animator_duration_scale 0
            ./gradlew connectedAndroidTest
      # - run:
      #     name: android testing
      #     command: ./gradlew connectedAndroidTest

# --exclude-task connectedDemoUitestDebugAndroidTest --exclude-task connectedMasterBasicDebugAndroidTest

  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/android:2023.02
    steps:
      - checkout
      - run:
          name: Build and deploy package
          command: |
            mvn clean deploy -Dmaven.repo.url=https://maven.pkg.github.com/tr-sangale/androidlibrary -Dmaven.deploy.skip=true -Dmaven.artifact.threads=5


workflows:
  build-androidTest-deploy:
    jobs:
      - build
      - android-test:
          requires:
            - build
      - deploy:
          requires:
            - android-test

